### ISSUE TITLE
pycharm-community-5.0.3-1.fc22.x86_64.rpm not signed

### ISSUE THREAD

**Issue by ndevln** [phracek/pycharm-community-edition#11]
DNF complains that the package **pycharm-community-5.0.3-1.fc22.x86_64.rpm** is not signed when updating. I don't know if it's an problem with the copr build service. 

$ cat _copr_phracek-PyCharm.repo 
```
[phracek-PyCharm]
name=Copr repo for PyCharm owned by phracek
baseurl=https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/pubkey.gpg
enabled=1
enabled_metadata=1
```

System: Fedora 22 x86_64

**Comment by jpopelka** [comment]
I've seen it too on F22.
pycharm-community-5.0.3-1.fc23 is OK.

**Comment by phracek** [comment]
I guess, It is related to COPR, not to PyCharm. Please report it to COPR team.
