### ISSUE TITLE
Git and tasks integrations break with `2016.1.4-2`

### ISSUE THREAD

**Issue by allanlewis** [phracek/pycharm-community-edition#16]
Upgrading from `2016.1.4-1` to `2016.1.4-2` appears to break the Git and tasks integrations. (By "tasks" I mean integration with issue trackers; I use it with JIRA.) This is 100% reproducible on my system (Fedora 23) by downgrading both `pycharm-community` and `pycharm-community-plugins` to `2016.1.4-1` (integrations work) and then upgrading to `2016.1.4-2` (integrations break).

(Aside: it would be great if the repo had tags, to make it easier to see the changes between releases.)

I'm not sure what diagnostic info would be useful: please advise and I'll see what I can do.

**Comment by phracek** [comment]
It was caused by my mistake in SPEC file.
I have built a new version, in meantime. 
@allanlewis Can you please share this dialog from PyCharm ( File -> Settings -> Plugins )

**Comment by phracek** [comment]
What kind of plugins do you use?

**Comment by allanlewis** [comment]
Here's my ![Plugins list](https://cloud.githubusercontent.com/assets/194736/15677112/c05ac138-2740-11e6-875b-24f985928fca.png). For example, I use the GitHub plugin.

**Comment by phracek** [comment]
The latest version available in COPR fixes Go and Markdown support.
CppTools plugin upstream https://github.com/nicity/CppTools is no longer maintain, I guess.
I have sent a PR for bumping supported PyCharm versionm though.  https://github.com/nicity/CppTools/pull/26

**Comment by TomasTomecek** [comment]
How about the git plugin? It still seems like I cannot use it. Am using `pycharm-community-plugins-2016.1.4-4.fc25.x86_64`.

**Comment by allanlewis** [comment]
That's also what I'm seeing.

**Comment by phracek** [comment]
I have the same problem. But Pycharm says, it requires Git4Idea plugin.
Plugin is located here https://github.com/JetBrains/intellij-community/tree/master/plugins/git4idea
I am not able to file a bug regarding Community Edition.

**Comment by TomasTomecek** [comment]
this seems to be the upstream issue tracker: https://youtrack.jetbrains.com/issues/IDEA

**Comment by allanlewis** [comment]
If the bug is PyCharm-specific, you can raise it in the PyCharm section: https://youtrack.jetbrains.com/issues/PY

**Comment by phracek** [comment]
I have filed an issues: https://youtrack.jetbrains.com/issue/PY-19852

**Comment by TomasTomecek** [comment]
In the meanwhile I downgraded to `2016.1.3-2.fc23` and it resolved my issue with the git plugin.

@phracek thanks for reporting it upstream! I hope we'll hear from them soon.

**Comment by allanlewis** [comment]
@TomasTomecek I'm using the Git plugin successfully with version `2016.1.4-1.fc23`. That version appears to have dropped off the COPR repo, but you can build it from commit `b8d8b97`.

**Comment by allanlewis** [comment]
@phracek, any updates on this? I haven't seen any response to your upstream bug report. In the past, JetBrains have been dismissive of any unsupported installation methods, so I'm not sure it's worth waiting. I tried reverting some of the commits since `b8d8b97`, but it's not clear exactly which change breaks everything; perhaps excluding the default plugins? (Building master with that reverted gave me errors in the "event log": presumably that was the motivation for that commit.)

**Comment by phracek** [comment]
Sorry I did not have a chance to look on it. I was on the vacation.

**Comment by phracek** [comment]
@TomasTomecek @allanlewis I have found a problem. This commit https://github.com/phracek/pycharm-community-edition/commit/237249ce962b5d42639a768f37c2b03490a8b36a removes plugins delivered by pycharm itself.

I am going to test it and immediately initiate new COPR build.

**Comment by phracek** [comment]
plugins were:  terminal, tasks, svn4idea, settings-repository, rest, python-rest, ipnb, github, git4idea

**Comment by allanlewis** [comment]
Thanks @phracek! I've installed this on Fedora 23 and both Git and Tasks seem to be working.

**Comment by TomasTomecek** [comment]
@allanlewis you lucky one!

```
39 kB/s | 121 MB     31:10 ETA
```

anyway, thanks @phracek!
