### ISSUE TITLE
Problem with i686 package at Fedora 24

### ISSUE THREAD

**Issue by nesnera** [phracek/pycharm-community-edition#17]
It seams there is a 64bit dependence (repo [phracek-PyCharm](https://copr.fedorainfracloud.org/coprs/phracek/PyCharm/)):
```
# dnf install pycharm-community
Last metadata expiration check: 0:13:35 ago on Tue Jul  5 09:10:52 2016.
Error: nothing provides libc.so.6(GLIBC_2.4)(64bit) needed by pycharm-community-2016.1.4-4.fc24.i686
(try to add '--allowerasing' to command line to replace conflicting packages)
```

**Comment by phracek** [comment]
@nesnera This is really strange. I have only requirements to Java. That's all.
What is output of command `uname -a`.
I guess you have installed  Fedora 24 32bit with bunch of 64bit packages, right?

**Comment by nesnera** [comment]
$ uname -a
Linux pb 4.6.3-300.fc24.i686 #1 SMP Fri Jun 24 21:29:36 UTC 2016 i686 i686 i386 GNU/Linux

I have no 64bit packages. I hope ;?)

**Comment by phracek** [comment]
I have found the problem. You are not able to install or even run 64bit binaries or libraries on 32 bit system with running 32bit kernel. Sorry:(
You should have at least 64 bit system or kernel.
