### ISSUE TITLE
PyCharm 2017.2.1 doesn't build because top-level directory in archive is wrongly-named

### ISSUE THREAD

**Issue by allanlewis** [phracek/pycharm-community-edition#39]
The top-level directory inside the Linux build archive for PyCharm 2017.2.1 is named `2017.2`, which breaks the spec file in this repo as it expects `%{name}-%{version}`, i.e. `pycharm-community-2017.2.1`. I have a patch on a local branch that fixes this by creating a new global variable, but it's not ideal. [This PyCharm bug](https://youtrack.jetbrains.com/issue/PY-25578) seems to capture the issue.

**Comment by phracek** [comment]
Closing issue. It is already fixed.
