### ISSUE TITLE
Get this into fedora and EPEL

### ISSUE THREAD

**Issue by stardust85** [phracek/pycharm-community-edition#4]
I already saw it in copr, does it mean it is incompatible with main fedora? I see that you don't compile it, you only pack the compiled content (that's not a-priori bad, I do it as well with lots of java 3rd-party apps in my company), so maybe this is the reason it has to be in copr?

**Comment by phracek** [comment]
Yeah, that's a reason why it is not in Fedora. I did not compile it. There are already 3rd party applications.
I did not ask https://www.jetbrains.com/pycharm/ yet if source codes are available?

In license is mentioned that it is a free, opensource, Apacha 2 license.

**Comment by stardust85** [comment]
Yes, the community edition is really free software :) https://github.com/JetBrains/intellij-community/tree/master/python

**Comment by stardust85** [comment]
You may be interested in this page https://fedoraproject.org/wiki/SIGs/Java, people there are asking for  IntelliJ IDEA, which is very similar.

**Comment by stardust85** [comment]
Maybe we can create a branch for this issue.

**Comment by phracek** [comment]
@stardust85 Feel free to do it.

**Comment by phracek** [comment]
@stardust85 Did you try to build it under Fedora? Are there some prerequisities from Java part?

I am going to create at least tarball and try to add them to Fedora. But I would like to be sure that no Java classes or JAR files are needed.

**Comment by stardust85** [comment]
I haven't tried to build it yet. And what's worse, it looks like I will not have time to do it in next months

**Comment by phracek** [comment]
@stardust85 Do you know how to download a tar ball with PyCharm? I will try during my free time build it.

**Comment by phracek** [comment]
@stardust85 Sorry for spam. Found it. https://github.com/JetBrains/intellij-community/releases

**Comment by Conan-Kudo** [comment]
@phracek Any progress on properly packaging IDEA/PyCharm for Fedora?

**Comment by phracek** [comment]
Personally, I don't have free time to investigate.

**Comment by phracek** [comment]
@Conan-Kudo @stardust85 I will soon create an PyCharm for Flatpak. FYI

**Comment by stardust85** [comment]
Very good idea. Probably makes more sense than a system package :)

**Comment by phracek** [comment]
FYI https://github.com/flathub/flathub/pull/166

**Comment by Conan-Kudo** [comment]
:/

**Comment by legoktm** [comment]
@phracek Will you keep maintaining the COPR repository or should we migrate to the flatpak? And, thank you for maintaining this :)

**Comment by phracek** [comment]
PyCharm is a part of flatpak.
@legoktm I will keep maintaining the COPR repository.
