### ISSUE TITLE
Build for Fedora 27

### ISSUE THREAD

**Issue by allanlewis** [phracek/pycharm-community-edition#46]
The Fedora 27 configuration is enabled in COPR, but there are no builds: can you please trigger a build? (I've requested build permission in COPR, feel free to deny that.)

**Comment by legoktm** [comment]
https://copr.fedorainfracloud.org/coprs/phracek/PyCharm/ lists a version for Fedora 27, and I'm also using it just fine on 27 so I think this can be closed now?

**Comment by allanlewis** [comment]
Agreed - thanks, @legoktm.
