### ISSUE TITLE
The repo doesn't integrate with GNOME Software

### ISSUE THREAD

**Issue by Sesivany** [phracek/pycharm-community-edition#47]
This Copr repo is now enabled as part of 3rd party software repos in Fedora. The application doesn't show up in Software though because of missing metadata in the yum repo.

The docs how to do it is here: https://github.com/developer-portal/content/pull/203

**Comment by xvitaly** [comment]
https://pagure.io/copr/copr/issue/2039

**Comment by xvitaly** [comment]
Should be fixed now.
