### ISSUE TITLE
Correct Java dependencies are not pulled in when installed on Fedora 28

### ISSUE THREAD

**Issue by thozza** [phracek/pycharm-community-edition#49]
When I installed pycharm-community from COPR on fresh installation of Fedora 28, PyCharm would not start:
```
aug 04 22:51:21 thozza-work-pc pycharm-community.desktop[21801]: Startup Error: Application cannot start in headless mode
```
After some googling, I came across https://stackoverflow.com/questions/27727826/problems-installing-pycharm and checked if I installed correct java packages:
```
$ rpm -qa | grep java
javapackages-tools-5.0.0-14.fc28.noarch
java-1.8.0-openjdk-headless-1.8.0.181-7.b13.fc28.x86_64
java-openjdk-10.0.2.13-1.fc28.x86_64
tzdata-java-2018e-1.fc28.noarch
abrt-java-connector-1.1.1-1.fc28.x86_64
java-openjdk-headless-10.0.2.13-1.fc28.x86_64
```
I definitely had non-headless Java installed (version 10.0.2.13) , but it apparently was not the right one. PyCharm RPM has dependency only on "java", without any further specification of the version. There are multiple versions of Java provided by different packages. After I manually installed **java-1.8.0-openjdk**, PyCharm started to work. I assume that this issue will not appear if you install any other package, before PyCharm, which will pull in this correct version of Java. Since PyCharm uses specific version of Java if there are multiple versions installed on the system, it would be probably good idea to have dependency on specific version of Java in the SPEC. This way the package manager would install also required non-headless version of Java.

**Comment by xvitaly** [comment]
Packaged OpenJDK is no longer required in 2021.1.1.
