### ISSUE TITLE
pycharm-community upgrade failed from 2019.3.2 to 2019.3.3

### ISSUE THREAD

**Issue by mharpau** [phracek/pycharm-community-edition#60]
I'm running Pycharm Community 2019 on Fedora 31.
When I tried to upgrade today from 2019.3.2 to 2019.3.3 I got below error:

=========================================================================================================
 Package                   Arch   Version           Repository                                      Size
=========================================================================================================
Upgrading:
 pycharm-community         x86_64 2019.3.3-1.fc31   copr:copr.fedorainfracloud.org:phracek:PyCharm 193 M
 pycharm-community-doc     noarch 2019.3.3-1.fc31   copr:copr.fedorainfracloud.org:phracek:PyCharm 329 k
 pycharm-community-jre     x86_64 2019.3.3-1.fc31   copr:copr.fedorainfracloud.org:phracek:PyCharm  93 M
 pycharm-community-plugins noarch 2019.3.3-1.fc31   copr:copr.fedorainfracloud.org:phracek:PyCharm 104 M

Transaction Summary
=========================================================================================================
Upgrade  4 Packages

Total size: 390 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] pycharm-community-2019.3.3-1.fc31.x86_64.rpm: Already downloaded                              
[SKIPPED] pycharm-community-doc-2019.3.3-1.fc31.noarch.rpm: Already downloaded                          
[SKIPPED] pycharm-community-jre-2019.3.3-1.fc31.x86_64.rpm: Already downloaded                          
[SKIPPED] pycharm-community-plugins-2019.3.3-1.fc31.noarch.rpm: Already downloaded                      
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/share/java/pycharm-community/plugins/editorconfig/lib/editorconfig.jar conflicts between attempted installs of pycharm-community-plugins-2019.3.3-1.fc31.noarch and pycharm-community-2019.3.3-1.fc31.x86_64
  file /usr/share/java/pycharm-community/plugins/editorconfig/lib/resources_en.jar conflicts between attempted installs of pycharm-community-plugins-2019.3.3-1.fc31.noarch and pycharm-community-2019.3.3-1.fc31.x86_64
  file /usr/share/java/pycharm-community/plugins/markdown/lib/markdown.jar conflicts between attempted installs of pycharm-community-plugins-2019.3.3-1.fc31.noarch and pycharm-community-2019.3.3-1.fc31.x86_64
  file /usr/share/java/pycharm-community/plugins/markdown/lib/resources_en.jar conflicts between attempted installs of pycharm-community-plugins-2019.3.3-1.fc31.noarch and pycharm-community-2019.3.3-1.fc31.x86_64

**Comment by imsedgar** [comment]
This dnf transaction error breaks automatic installation of updates on Fedora 31 (running timer / service dnf-automatic-install). No packages will be updated until this is fixed!

I can run updates manually by
`dnf upgrade --exclude=pycharm\*`
but it is not feasible for many computers.

Please can it be fixed soon?
Many thanks in advance!

**Comment by phracek** [comment]
@xvitaly Can you please look at this issue? It is caused by splitting pycharm-community.spec into two SPEC files. Thank you in advance

**Comment by xvitaly** [comment]
> Can you please look at this issue?

PyCharm authors added some plugins into the core tarball. I will fix this soon and rebuild -plugins subpackage.

**Comment by xvitaly** [comment]
Should be fixed now. Thanks for report.
