### ISSUE TITLE
2023.3.2-1 dependency failure on EL8

### ISSUE THREAD

**Issue by jonsattelberger** [phracek/pycharm-community-edition#68]
Attempting to update from 2023.1.4-1 to 2023.3.2-1 fails on RHEL 8, due to failure to resolve a dependency for pycharm-community-plugins:
```
Error: 
 Problem: problem with installed package pycharm-community-plugins-2023.1.4-1.el8.x86_64
  - package pycharm-community-plugins-2023.1.4-1.el8.x86_64 from @System requires pycharm-community(x86-64) = 2023.1.4, but none of the providers can be installed
  - package pycharm-community-plugins-2023.1.4-1.el8.x86_64 from phracek-PyCharm_phracek-PyCharm-epel8 requires pycharm-community(x86-64) = 2023.1.4, but none of the providers can be installed
  - cannot install both pycharm-community-2023.3.2-1.el8.x86_64 from phracek-PyCharm_phracek-PyCharm-epel8 and pycharm-community-2023.1.4-1.el8.x86_64 from @System
  - cannot install the best update candidate for package pycharm-community-2023.1.4-1.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
https://copr.fedorainfracloud.org/coprs/phracek/PyCharm/build/7008915/

**Comment by nathancurry** [comment]
I ran into this on fc40 running `dnf install pycharm*`.  It appears the pycharm-community-plugins package is no longer being updated, but the out of date version is still being accidentally pipelined into the repo.

Based on a quick review of [the spec file](https://github.com/phracek/pycharm-community-edition/blob/master/pycharm-community-plugins.spec) it looks like these are just plugins available via the Plugins search in the app.

My guess is the pycharm-community-plugins is done for, and the workaround is to remove the package and install Plugins inside the app.

**Comment by jonsattelberger** [comment]
Looks like the issue has been resolved with recent builds.
